name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo gem install bundler jekyll
          sudo bundle install

      - name: Build site
        run: |
          bundle exec jekyll build

